{"uuid": "35fbca52-e455-4248-bd0d-0ab86327e21d", "children": ["6b04b11b-fd01-4b1d-84f5-9398d5b64937"], "befores": [{"name": "super_admin", "status": "broken", "statusDetails": {"message": "UnboundLocalError: cannot access local variable 'url' where it is not associated with a value\n", "trace": "  File \"C:\\Apps\\teamcity-tests\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Apps\\teamcity-tests\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Apps\\teamcity-tests\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Apps\\teamcity-tests\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Apps\\teamcity-tests\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Apps\\teamcity-tests\\tests\\backend\\conftest.py\", line 60, in super_admin\n    super_admin.api_manager.auth_api.auth_and_get_csrf_token(super_admin.creds)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Apps\\teamcity-tests\\api\\auth_api.py\", line 11, in auth_and_get_csrf_token\n    csrf_token = self.send_request('GET', '/authenticationTest.html?csrf').text\n                 ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Apps\\teamcity-tests\\custom_requester\\custom_requester.py\", line 17, in send_request\n    with allure.step(f'Sending {method} request to {url} with data: {data}, expected_status: {expected_status}'):\n                                                    ^^^\n"}, "steps": [{"name": "Auth user with creds: \"('', '8333446226969871276')\" and get csrf token", "status": "broken", "statusDetails": {"message": "UnboundLocalError: cannot access local variable 'url' where it is not associated with a value\n", "trace": "  File \"C:\\Apps\\teamcity-tests\\api\\auth_api.py\", line 11, in auth_and_get_csrf_token\n    csrf_token = self.send_request('GET', '/authenticationTest.html?csrf').text\n                 ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Apps\\teamcity-tests\\custom_requester\\custom_requester.py\", line 17, in send_request\n    with allure.step(f'Sending {method} request to {url} with data: {data}, expected_status: {expected_status}'):\n                                                    ^^^\n"}, "start": 1745837796985, "stop": 1745837796985}], "start": 1745837796985, "stop": 1745837796985}], "start": 1745837796985, "stop": 1745837796997}